spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory2?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 80B2EBCE9A51C318@MonolithIoT
server:
  port: 5601
tcp-api:
  ip: 127.0.0.1
  port: 8100
serial:
  baudRate: 115200
logging:
  level:
    com.berrontech.dsensor: debug