spring:
  application:
    name: digital-sensor-dirver-server
  profiles:
    active: @profiles.active@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
pagehelper:
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:mappers/*.mapper.xml
  type-aliases-package: com.berrontech.dsensor.dataserver.common.entity
server:
  tomcat:
    threads:
      min-spare: 2
db-upgrade:
  db-init-sql-file: db_init.sql
  script-path: classpath:/db_script
  target-db-version: 14
serial:
  lib-name: native_lib/libserial_port
app:
  app-version: 0.3.4
log-conf:
  log-keep-days: 30