spring:
  application:
    name: digital-sensor-dirver-server
  profiles:
    active: @profiles.active@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
pagehelper:
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:mappers/*.mapper.xml
  type-aliases-package: com.berrontech.dsensor.dataserver.common.entity