spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scada_wsa?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: monolithiot
server:
  port: 5601
tcp-api:
  ip: 127.0.0.1
  port: 8100
logging:
  config: classpath:logback-spring-test.xml
log-conf:
  log-file-dir: /opt/weight_slot/log