spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scada_wsa?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: monolithiot
server:
  port: 5601
tcp-api:
  ip: 127.0.0.1
  port: 8100
serial:
  lib-path: /opt/weight_slot/so/libserial_port.so
logging:
  config: classpath:logback-spring-test.xml
db-upgrade:
  db-version-file-path: /opt/weight_slot/db/db_version.json
  script-path:  /opt/weight_slot/db
log-conf:
  log-file-dir: /opt/weight_slot/log