spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scada_wsa?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 5601
tcp-api:
  ip: 47.96.151.141
  port: 10010
logging:
  config: classpath:logback-spring-test.xml
log-conf:
  log-file-dir: E:\FileWork