spring:
  datasource:
    url: jdbc:mysql://192.168.0.187:3306/db_weight_slot?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: usernameforU
    password: MyPassword*123
server:
  port: 5601
tcp-api:
  ip: 127.0.0.1
  port: 8100
serial:
  lib-path: /sdcard/scada_wsa/so/libserial_port.so
logging:
  config: classpath:logback-spring-dev.xml
